### ISSUE TITLE
HandlerContext update_changes translates empty string to BaseModel instance

### ISSUE THREAD

**Issue by bartv** [inmanta/inmanta#2537] opened 2020-11-25 11:27 UTC
It seems that the code in update_changes translates an empty string to an instance of BaseModel. The following patch updates a test case to reproduce it:

```diff
diff --git a/tests/test_agent.py b/tests/test_agent.py
index 6f1e874c..44b3551a 100644
--- a/tests/test_agent.py
+++ b/tests/test_agent.py
@@ -63,6 +63,12 @@ def test_context_changes():
     assert len(ctx.changes) == 1
     assert isinstance(ctx.changes["value"], AttributeStateChange)
 
+    # use dict with empty string
+    ctx.update_changes({"value": dict(current="", desired="value")})
+    assert len(ctx.changes) == 1
+    assert ctx.changes["value"].current == ""
+    assert ctx.changes["value"].desired == "value"
+
     # use tuple
     ctx.update_changes({"value": ("a", "b")})
     assert len(ctx.changes) == 1
```

**Comment by bartv** [comment] 2020-11-25 11:32
The most basic piece of code:

```python
x = AttributeStateChange(current="", desired="abc")
assert not isinstnace(x.current, BaseModel)
```

**Comment by sanderr** [comment] 2020-11-26 09:54
#2540 describes the root cause as illustrated by the snippet above.

**Comment by sanderr** [comment] 2020-11-26 10:01
#2540 has been updated to include all information included here. Closing this one.

**Closed by sanderr** 2020-11-26 10:01 UTC
Labels: agent, bug
