### ISSUE TITLE
Git does not use environment variables

### ISSUE THREAD

**Issue by bartv** [inmanta/inmanta#2413] opened 2020-10-09 12:59 UTC
When a http_proxy is set in /etc/sysconfig/imanta-server this is used by pip when installing dependencies but it is ignored by git. Setting it in $HOME/.gitconfig also does not work, which might be due to not having $HOME set.

The code does pass the environment variables: https://github.com/inmanta/inmanta/blob/master/src/inmanta/module.py#L123

It is worked around by setting /etc/gitconfig for the entire system.

This issue was reported in support ticket zendesk#33

We do not have an http proxy to test this. However, there are many [environment variables](https://git-scm.com/book/en/v2/Git-Internals-Environment-Variables) of which some could be used to debug the issue.

**Comment by kazaamjt** [comment] 2020-11-09 13:52
Wrote a simple test that sets the GIT_TRACE to true and checked the git output (by removing the subprocess.check_call stdout pipe to devnull.
In my debug pytest output, the git trace showed up like expected.
I will attempt setting up a proxy and see if it is anything to do with proxy settings specifically, but ENV variables seem to work.

**Comment by bartv** [comment] 2020-11-09 17:51
The customer saw this on centos 7, which is also a quite old git version

**Comment by kazaamjt** [comment] 2020-11-13 11:28
Using centos 7, python 3.6 and git 1.8, I was unable to reproduce this, for now.
Reassigning to Bart as discussed.

**Comment by bartv** [comment] 2020-11-19 09:55
Unable to reproduce. I will close this issue.

**Comment by bartv** [comment] 2020-11-23 14:57
We found the issue:

https://github.com/inmanta/inmanta/blob/master/src/inmanta/server/services/compilerservice.py#L166
https://github.com/inmanta/inmanta/blob/master/src/inmanta/server/services/compilerservice.py#L171

**Comment by bartv** [comment] 2020-11-23 14:58
A test case can be created setting the gittrace env variable and checking for git trace data in the compiler log

**Comment by bartv** [comment] 2020-11-23 14:59
```
diff --git a/src/inmanta/server/services/compilerservice.py b/src/inmanta/server/services/compilerservice.py
index 1015b58a..0622a7af 100644
--- a/src/inmanta/server/services/compilerservice.py
+++ b/src/inmanta/server/services/compilerservice.py
@@ -163,7 +163,7 @@ class CompileRun(object):
                 env_all.update(env)
 
             sub_process = await asyncio.create_subprocess_exec(
-                cmd[0], *cmd[1:], stdout=subprocess.PIPE, stderr=subprocess.PIPE, cwd=cwd, env=env
+                cmd[0], *cmd[1:], stdout=subprocess.PIPE, stderr=subprocess.PIPE, cwd=cwd, env=env_all
             )
 
             returncode = await self.drain(sub_process)
```

**Closed** 2020-11-24 12:52 UTC
Labels: bug, support
