### ISSUE TITLE
Support loading all source files in plugins dir of modules on the agent

### ISSUE THREAD

**Issue by bartv** [inmanta/inmanta#2162] opened 2020-06-05 12:49 UTC
Currently, the agent only gets the source code of the __init__.py file. With the new inmanta_plugins namespace package we can support all files. For big modules this allows for cleaner code.

**Comment by sanderr** [comment] 2020-07-01 14:52
Could you provide some more context here? I understand the goal but I haven't got a clue where to look (searching for "__init__.py" is not very effective).

**Comment by wouterdb** [comment] 2020-07-01 14:56
points you have to look for

- exporter collects and sends all the files
- server stores them (both the files and the association of a resource with a file)
- agent pulls them in 
- agent load them

You will have to update all these parts, if I'm not mistaken.

**Comment by bartv** [comment] 2020-07-01 14:58
But description is not entirely correct. Currently the compiler loads all *.py files and so everything with an @resource or @handler annotation will be loaded. However, you cannot have any helper modules or subpackages.

**Comment by wouterdb** [comment] 2020-07-01 14:59
In this case, the problem is not the loading per-se but the sending over. The loading problem should be fixed already.

**Comment by wouterdb** [comment] 2020-07-01 14:59
The `CodeService` is the server part, from there you should be able to find the other parts.

**Comment by bartv** [comment] 2020-07-01 15:01
> In this case, the problem is not the loading per-se but the sending over. The loading problem should be fixed already.

It was years ago, std has had resources.py since forever.

**Closed** 2020-07-09 12:48 UTC
