### ISSUE TITLE
Compiler fails silently when std cannot be loaded

### ISSUE THREAD

**Issue by bartv** [inmanta/inmanta#1767] opened 2020-02-03 19:17 UTC
Create a project with repo set to a value that does not exist. When an empty main.cf is compiled, only an empty line is printed. 

When compile is invoked with -X the following trace is printed:
```
Traceback (most recent call last):
  File "/home/bart/workspace/inmanta/src/inmanta/module.py", line 564, in load_module
    self, module_name, list(parse_requirements(module_name)), install_mode=self._install_mode
  File "/home/bart/workspace/inmanta/src/inmanta/module.py", line 807, in install
    raise InvalidModuleException("could not locate module with name: %s" % modulename)
inmanta.module.InvalidModuleException: could not locate module with name: std

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/bart/workspace/inmanta/src/inmanta/module.py", line 535, in load_module_recursive
    module = self.get_module(module_name)
  File "/home/bart/workspace/inmanta/src/inmanta/module.py", line 510, in get_module
    return self.load_module(module_name)
  File "/home/bart/workspace/inmanta/src/inmanta/module.py", line 569, in load_module
    raise InvalidModuleException("Could not load module %s" % module_name) from e
inmanta.module.InvalidModuleException: Could not load module std

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bart/workspace/inmanta/src/inmanta/app.py", line 627, in app
    options.func(options)
  File "/home/bart/workspace/inmanta/src/inmanta/app.py", line 258, in compile_project
    result = do_compile()
  File "/home/bart/workspace/inmanta/src/inmanta/compiler/__init__.py", line 44, in do_compile
    (statements, blocks) = compiler.compile()
  File "/home/bart/workspace/inmanta/src/inmanta/compiler/__init__.py", line 146, in compile
    project.load()
  File "/home/bart/workspace/inmanta/src/inmanta/module.py", line 447, in load
    self.get_complete_ast()
  File "/home/bart/workspace/inmanta/src/inmanta/module.py", line 490, in get_complete_ast
    for _, nstmt, nb in self.load_module_recursive(imports):
  File "/home/bart/workspace/inmanta/src/inmanta/module.py", line 549, in load_module_recursive
    raise ModuleNotFoundException(ns, imp, e)
  File "/home/bart/workspace/inmanta/src/inmanta/ast/__init__.py", line 690, in __init__
    WrappingRuntimeException.__init__(self, stmt, msg, cause)
  File "/home/bart/workspace/inmanta/src/inmanta/ast/__init__.py", line 599, in __init__
    RuntimeException.__init__(self, stmt=stmt, msg=msg)
  File "/home/bart/workspace/inmanta/src/inmanta/ast/__init__.py", line 526, in __init__
    self.set_location(stmt.get_location())
  File "/home/bart/workspace/inmanta/src/inmanta/ast/statements/__init__.py", line 58, in get_location
    return self.location
  File "/home/bart/workspace/inmanta/src/inmanta/ast/__init__.py", line 131, in get_location
    assert self._location is not None
AssertionError
```

**Comment by sanderr** [comment] 2020-02-07 14:17
duplicate of #1480

**Closed** 2020-02-11 12:18 UTC
Labels: bug, compiler
