### ISSUE TITLE
Module requirements installer ignores environment markers (PEP 508)

### ISSUE THREAD

**Issue by sanderr** [inmanta/inmanta#2363] opened 2020-09-17 09:43 UTC
`inmanta.env.VirtualEnv._gen_requirements_file` calls `pkg_resources.parse_requirements` but ignores the result's `marker` attribute. Among other possible undesired behaviors, this causes a dependency like `dataclasses~=0.7;python_version<'3.7'` (as can be found in the std module) to fail to install on Python >= 3.7.

**Comment by arnaudsjs** [comment] 2020-09-17 09:48
This is a duplicate of #2359

**Closed** 2020-09-17 10:01 UTC
Labels: bug
